spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chefhat_detection?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: while(0725)ztyLogin[Mysql]++1
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.dbtest.dbkeshe.entity
server:
  port: 8181

pagehelper:
  helper-dialect: mysql
  reasonable: true
